[package]
name = "sanka"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
hyper = "~0.7.2"
concurrent-hashmap = { git = "https://github.com/veddan/rust-concurrent-hashmap.git" }
bip_bencode = "~0.1.2"
time = "~0.1"
url = "~0.5.5"

[profile.dev]
debug = true
